### ISSUE TITLE
Quite often crash on devices below android 5.0 during screen orientation change

### ISSUE THREAD

**Issue by Wojtek1234** [iamMehedi/MVBarcodeReader#5]
java.lang.RuntimeException: Fail to connect to camera service
                                                                at android.hardware.Camera.native_setup(Native Method)
                                                                at android.hardware.Camera.<init>(Camera.java:366)
                                                                at android.hardware.Camera.open(Camera.java:313)
                                                                at devliving.online.mvbarcodereader.camera.CameraSource.createCamera(CameraSource.java:738)
                                                                at devliving.online.mvbarcodereader.camera.CameraSource.start(CameraSource.java:362)
                                                                at devliving.online.mvbarcodereader.camera.CameraSourcePreview.startIfReady(CameraSourcePreview.java:90)
                                                                at devliving.online.mvbarcodereader.camera.CameraSourcePreview.access$200(CameraSourcePreview.java:32)
                                                                at devliving.online.mvbarcodereader.camera.CameraSourcePreview$SurfaceCallback.surfaceCreated(CameraSourcePreview.java:113)
                                                                at android.view.SurfaceView.updateWindow(SurfaceView.java:548)
                                                                at android.view.SurfaceView.access$000(SurfaceView.java:85)
                                                                at android.view.SurfaceView$3.onPreDraw(SurfaceView.java:173)
                                                                at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:671)
                                                                at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1828)
                                                                at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1008)
                                                                at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4222)
                                                                at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
                                                                at android.view.Choreographer.doCallbacks(Choreographer.java:555)
                                                                at android.view.Choreographer.doFrame(Choreographer.java:525)
                                                                at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
                                                                at android.os.Handler.handleCallback(Handler.java:615)
                                                                at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                at android.os.Looper.loop(Looper.java:137)
                                                                at android.app.ActivityThread.main(ActivityThread.java:4793)
                                                                at java.lang.reflect.Method.invokeNative(Native Method)
                                                                at java.lang.reflect.Method.invoke(Method.java:511)
                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:808)
                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:575)
                                                                at dalvik.system.NativeStart.main(Native Method)

**Comment by iamMehedi** [comment]
@Wojtek1234 can you please try ae2e311
